input: # files to use
    prompt: ../../../Analyses/pp5TeV/Ds_wML_mult/inputs/MC/ml/Prompt_Dspp5TeV_pT_1_50.parquet.gzip
    FD: ../../../Analyses/pp5TeV/Ds_wML_mult/inputs/MC/ml/FD_Dspp5TeV_pT_1_50.parquet.gzip
    data: ../../../Analyses/pp5TeV/Ds_wML_mult/inputs/data/ml/Data_Dspp5TeV_pT_1_50.parquet.gzip

output:
    leg_labels: ['Background', 'Prompt D$_s$', 'Feed-down D$_s$'] # legend labels
    out_labels: ['Bkg', 'Prompt', 'FD'] # output labels
    dir: '../../../Analyses/pp5TeV/Ds_wML_mult/ml_training' # output dir

pt_ranges: # ranges in pt to split the data in the ml training and testing
    min: [1, 2, 4, 6, 12] # list
    max: [2, 4, 6, 12, 50] # list

filtering:
    bkg_mass: inv_mass < 1.832 or inv_mass > 2.012 # pandas query to select bkg candidates

ml:
    training_columns: [cos_p_xy, d_len, norm_dl_xy, sig_vert, delta_mass_KK, cos_PiKPhi_3,
                       max_norm_d0d0exp, nsigComb_Pi_0, nsigComb_Pi_1, nsigComb_Pi_2, nsigComb_K_0, nsigComb_K_1, nsigComb_K_2] 
                       # list of training variables
    plotting_columns: [inv_mass, pt_cand, cos_p_xy, d_len, norm_dl_xy, sig_vert, delta_mass_KK, cos_PiKPhi_3,
                       max_norm_d0d0exp, nsigComb_Pi_0, nsigComb_Pi_1, nsigComb_Pi_2, nsigComb_K_0, nsigComb_K_1, nsigComb_K_2] 
                       # list of variables to plot
    hyper_par: {'max_depth':3, 'learning_rate':0.05, 'n_estimators':400, 'min_child_weight':5, 'colsample':0.9, 'n_jobs':4, 'tree_method':hist}
