pp5TeVPrompt:
    Meson: 'Dplus'
    FixSigma: 0
    SigmaFile: ''
    SigmaMultFactor: 1.
    FixMean: 0
    MeanFile: ''
    PtMin: [ 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 16, 24]   
    PtMax: [ 2, 3, 4, 5, 6, 7, 8, 10, 12, 16, 24, 36]
    MassMin: [ 1.74, 1.74, 1.74, 1.74, 1.74, 1.74, 1.74, 1.74, 1.74, 1.74, 1.74, 1.74]    
    MassMax: [ 2.00, 2.00, 2.00, 2.00, 2.00, 2.00, 2.00, 2.00, 2.00, 2.00, 2.00, 2.00]
    Rebin: [ 5, 5, 5, 5, 6, 6, 6, 6, 8, 8, 10, 10]
    InclSecPeak: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    UseLikelihood: 1
    BkgFunc: [ 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo']
    SgnFunc: [ 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus']

pp5TeVFD:
    Meson: 'Dplus'
    FixSigma: 0
    SigmaFile: ''
    SigmaMultFactor: 1.
    FixMean: 0
    MeanFile: ''
    PtMin: [ 1, 2, 3, 4, 5, 6, 7, 8, 10, 12]
    PtMax: [ 2, 3, 4, 5, 6, 7, 8, 10, 12, 16]
    MassMin: [ 1.74, 1.74, 1.74, 1.74, 1.74, 1.74, 1.74, 1.74, 1.74, 1.74] 
    MassMax: [ 2.00, 2.00, 2.00, 2.00, 2.00, 2.00, 2.00, 2.00, 2.00, 2.00]
    Rebin: [ 5, 5, 5, 5, 6, 6, 6, 6, 8, 8 ]
    InclSecPeak: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
    UseLikelihood: 1
    BkgFunc: [ 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo']
    SgnFunc: [ 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus']

