infile:
    isMC: 1
    filename: [~/cernbox/Analyses/pp5TeV/Ds_wML_mult/inputs/MC/AnalysisResults_Dspp5TeV_pT_1_50.root]
    dirname: PWGHF_D2H_InvMassDs_TreeCreator_MC
    treename: treeMLDs

outfile:
    dirpath: ~/cernbox/Analyses/pp5TeV/Ds_wML_mult/inputs/MC/ml
    suffix: _Dspp5TeVNoOutlier
    treename: treeMLs
    
skimming:
    pt:
        min: 1
        max: 50
    preselections: nsigComb_Pi_0 > 0 and nsigComb_Pi_1 > 0 and nsigComb_Pi_2 > 0 and 
                   nsigComb_K_0 > 0 and nsigComb_K_1 > 0 and nsigComb_K_2 > 0 #null if you don't want to apply preselections
    colstokeep: [] #empty list if you want to keep everything
