infiles:
    signal:
        prompt:
            filename: ~/cernbox/ALICE_WORK/AnalysisNonPromptDpp2017/Dplus/outputs/ML/pt2_3/Prompt_pT_2_3_ModelApplied.parquet.gzip
            dirname: null
            treename: null
        feeddown:
            filename: ~/cernbox/ALICE_WORK/AnalysisNonPromptDpp2017/Dplus/outputs/ML/pt2_3/FD_pT_2_3_ModelApplied.parquet.gzip
            dirname: null
            treename: null
    secpeak: # only for Ds
        prompt:
            filename: null
            dirname: null
            treename: null
        feeddown:
            filename: null
            dirname: null
            treename: null
        mean: -1. # fixed values of mean and sigma if > 0 overwrite the use of the histogram
        sigma: -1.
    background:
        filename: ~/cernbox/ALICE_WORK/AnalysisNonPromptDpp2017/Dplus/outputs/ML/pt2_3/Data_pT_2_3_ModelApplied.parquet.gzip
        dirname: null
        treename: null
        nEvents: 950000000 # number of events for bkg in dataframe
        fractiontokeep: 0.1 
        isMC: false # if false bkg from SB
        fitFunc: pol2 # fit function for bkg from SB, e.g. pol1, pol2, expo
        nSigma: 4 # number of sigma from signal region, used to select SB

    preseleff: 
        filename: ~/cernbox/ALICE_WORK/AnalysisNonPromptDpp2017/Dplus/outputs/efficiency/EffDplus_Presel.root
        prompthistoname: hEffPrompt
        feeddownhistoname: hEffFD
    acceptance: ~/cernbox/ALICE_WORK/DmesonAnalysis/accfiles/Acceptance_Toy_DplusKpipi_yfidPtDep_etaDau09_ptDau100_FONLL5ptshape.root

predictions:
    crosssec:
        filename: ~/cernbox/ALICE_WORK/DmesonAnalysis/models/D0DplusDstarPredictions_502TeV_y05_noYShift_all_191017_BDShapeCorrected.root
        histonames: 
            prompt: hDpluskpipipred_max
            feeddown: hDpluskpipifromBpred_max_corr
    Raa: 
        prompt: 1. # can either be a fixed value or a text file
        feeddown: 1. # can either be a fixed value or a text file

nExpectedEvents: 950000000
sigmaMB: 50.87e+9 #pb
Taa: 1.
ptmin: [2]
ptmax: [3]

cutvars:
    ML_output_Bkg:
        min: 0.001
        max: 0.05
        step: 0.001
        upperlowercut: Upper
    ML_output_Prompt:
        min: 0.1
        max: 0.5
        step: 0.005
        upperlowercut: Lower
