isMC: no
filename: ../ML_DsAnalysis/QM_prel/inputs/data/AnalysisResultsDs_Data_010_3050_18qr_Tot_wTRcut.root
dirname: PWG3_D2H_InvMassDs_MLappl3050_pt8_50
listname: coutputDs_MLappl3050_pt8_50
sparsenameAll: fnSparse
normname: NormalizationCounter
histoevname: hNEvents
enableSecPeak: no #always no for data
