isMC: no
filename: ../ML_DsAnalysis/QM_prel/inputs/data/010_run_041019/AnalysisResultsDs_Data_010_18qr_Tot_wTRcut.root
dirname: PWG3_D2H_InvMassDs_MLappl010_pt2_8
listname: coutputDs_MLappl010_pt2_8
sparsenameAll: fnSparse
normname: NormalizationCounter
histoevname: hNEvents
enableSecPeak: no #always no for data
