Cent010:
    Meson: 'Ds'
    FixSigma: 0
    SigmaFile: ''
    SigmaMultFactor: 1.
    FixMean: 0
    MeanFile: ''
    PtMin: [2]    
    PtMax: [3]    
    MassMin: [1.78]    
    MassMax: [2.10]
    Rebin: [3]
    InclSecPeak: [1]
    UseLikelihood: 1
    BkgFunc: ['kExpo']
    SgnFunc: ['kGaus']

Cent3050:
    Meson: 'Ds'
    FixSigma: 0
    SigmaFile: 'outputs/fine_bin/raw_yields/RawYields_Ds_MC_3050_100419cuts_Improver.root'
    SigmaMultFactor: 1.
    FixMean: 0
    MeanFile: ''
    PtMin: [2]    
    PtMax: [3]    
    MassMin: [1.78]    
    MassMax: [2.10]
    Rebin: [4]
    InclSecPeak: [1]
    UseLikelihood: 1
    BkgFunc: ['kExpo']
    SgnFunc: ['kGaus']
