isMC: no
filename: inputs/AnalysisResults_Raa_Data_loose_3050_LHC18qr_pass1_Tot_run1383_4.root
dirname: PWG3_D2H_InvMassDs_3050_kSemiCentral_strongPIDpt8_loosecuts
listname: coutputDs_3050_kSemiCentral_strongPIDpt8_loosecuts
sparsenameAll: fnSparse
normname: NormalizationCounter
histoevname: hNEvents
enableSecPeak: no #always no for data
