isMC: yes
filename: /Users/fabrizio/cernbox/ALICE_WORK/Files/Trains/Run2/LHC19c3a/AnalysisResults_Ds_010_LooseCuts.root
dirname: PWG3_D2H_InvMassDs_010_LooseCuts_strongPIDpt8_Raa
listname: coutputDs_010_LooseCuts_strongPIDpt8_Raa
sparsenameAll: fnSparseReco_fromC
sparsenamePrompt: fnSparseReco_fromC
sparsenameFD: fnSparseReco_fromB
sparsenameGenPrompt: fnSparseAcc_fromC
sparsenameGenFD: fnSparseAcc_fromB
enableSecPeak: yes
sparsenamePromptSecPeak: fnSparseRecoDplus_fromC
sparsenameFDSecPeak: fnSparseRecoDplus_fromB
sparsenameGenPromptSecPeak: fnSparseAccDplus_fromC
sparsenameGenFDSecPeak: fnSparseAccDplus_fromB
normname: NormalizationCounter
histoevname: hNEvents