isMC: no
filename: /Users/fabrizio/cernbox/ALICE_WORK/Files/Trains/Run2/LHC18qr/AnalysisResults_Ds_3050.root
dirname: PWG3_D2H_InvMassDs_3050_2015Cuts_strongPIDpt8_Raa
listname: coutputDs_3050_2015Cuts_strongPIDpt8_Raa
sparsenameAll: fnSparse
normname: NormalizationCounter
histoevname: hNEvents
enableSecPeak: no #always no for data
