isMC: yes
filename: ~/cernbox/ALICE_WORK/Files/Trains/Run2/LHC18a4a2/AnalysisResults_Dplus_Loose_MB_Tree.root
dirname: PWG3_D2H_InvMassDplus
listname: coutputDplusLoose_kMB0100
sparsenameAll: hMassPtCutVarsAll
sparsenamePrompt: hMassPtCutVarPrompt
sparsenameFD: hMassPtCutVarsBfeed
sparsenameGenPrompt: hMCAccPrompt
sparsenameGenFD: hMCAccBFeed
enableSecPeak: no #no second peak for D+
sparsenamePromptSecPeak: null
sparsenameFDSecPeak: null
sparsenameGenPromptSecPeak: null
sparsenameGenFDSecPeak: null
normname: coutputDplusNormLoose_kMB0100
histoevname: fHistNEvents

#info for trees (files can be different if trees are filtered or with applied ML models)
tree:
    meson: Dplus #needed to define binning for invariant-mass histo
    filenameAll: null #not needed for MC
    filenamePrompt: ~/cernbox/ALICE_WORK/Files/Trains/Run2/LHC18a4a2/AnalysisResults_Dplus_Loose_MB_Tree.root
    filenameFD: ~/cernbox/ALICE_WORK/Files/Trains/Run2/LHC18a4a2/AnalysisResults_Dplus_Loose_MB_Tree.root
    dirname: PWG3_D2H_InvMassDplus
    treename: treeMLDs
